apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv-grafana
  labels:
    app: grafana

spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/data/grafana"
