apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: prometheus-pvc
  labels:
    name: prometheus-pvc

spec:
  storageClassName: manual
  accessModes:
  -  ReadWriteOnce

  resources:
    requests:
      storage: 5Gi